apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-sample
  labels:
    app: nginx-sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-sample
  template:
    metadata:
      labels:
        app: nginx-sample
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-sample
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx-sample
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-sample
  annotations:
    # External DNS annotation - this will create/update the DNS record
    external-dns.alpha.kubernetes.io/hostname: nginx.aiscaler.ai
    # NGINX Ingress Controller annotations
    kubernetes.io/ingress.class: "nginx"
    # cert-manager annotations
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - nginx.aiscaler.ai
    secretName: nginx-tls-cert
  rules:
  - host: nginx.aiscaler.ai
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-sample
            port:
              number: 80